### PR TITLE
Publish to plugin portal

### PR DESCRIPTION
**Pull request by AdrianRaFo**
Publish plugin to the gradle plugin portal
Release 0.8.1
Super thanks to @rachelcarmena :sun_with_face:

### CODE REVIEW

**Comment by rachelcarmena** [comment]
Awesome :raised_hands: Did you request the secrets to publish it with the 47Deg account?

**Comment by fedefernandez** [comment]
@franciscodr could you please add the secrets to this repo? Thanks

**Comment by rachelcarmena** [comment]
> @franciscodr could you please add the secrets to this repo? Thanks

I think Travis is being used here...

**Comment by franciscodr** [comment]
Working on it

**Comment by franciscodr** [comment]
@fedefernandez Done. I have published the secrets in Travis as `GRADLE_PUBLISH_KEY` and `GRADLE_PUBLISH_SECRET`

**Comment by rachelcarmena** [comment]
@AdrianRaFo , please, let me know when you push the button to take a look :sweat_smile:

**Pull request merged**
